var Map1 = [
    {},
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 0,
        X: 0,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
    {
        isjump: false,
        isStream: false,
        isClicble: true,
        CirclePoint: 0,
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
        Timing_beforeid: undefined,
        Timing_50id: undefined,
        Timing_100id: undefined,
        Timing_300id: undefined,
        Timing_100id2: undefined,
        Timing_50id2: undefined,
    },
]