/* for 
300 score	80 - 6 × OD
    100 score	140 - 8 × OD
    50 score	200 - 10 × OD


    Timing_0id: 0,
    Timing_50id: 10,
    Timing_100id: 8,
    Timing_300id: 6,

    */
var Map1 = {
    Map_Object1: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object2: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object3: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object4: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object5: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object6: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object7: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object8: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object9: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object10: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object11: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object12: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object13: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object14: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object15: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object16: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object17: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object18: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object19: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object20: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object21: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object22: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object23: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object24: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object25: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object26: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object27: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object28: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object29: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
    Map_Object30: {
        Y: 15,
        X: 25,
        Score_Animation_id: 0,
        Score_Animation_var: 0,
        Out_line_Animation_id: 0,
        Out_line_Animation_var: 0,
    },
}